### ISSUE TITLE
Geofencing API - Add "format: uri" to notificationUrl 

### ISSUE THREAD

**Issue by patrice-conil** [camaraproject/DeviceLocation#118]
**Problem description**
To have a strong typed notificationUrl, add a format constraint on type. 
This will simplify implementation and clarify usage.
```yaml
    NotificationUrl:
      type: string
      format: uri
      example: "https://application-server.com"
      description: https callback address where the event notification must be POST-ed
```
