### ISSUE TITLE
Use object name in discriminator mapping

### ISSUE THREAD

**Issue by patrice-conil** [camaraproject/DeviceLocation#121]
**Problem description**
In Area, the mapping uses CIRCLE to reference the Circle object... but CIRCLE should be Circle

**Expected behavior**
The left side of the mapping should be the object name, as explained in the design guidelines, to simplify implementation and consumption.

**Alternative solution**
```yaml
        mapping:
          Circle: "#/components/schemas/Circle"

    AreaType:
      type: string
      description: |
        Type of this area.
        Circle - The area is defined as a circle.
      enum:
        - Circle
```
