### ISSUE TITLE
Correct YAML examples to use upper case enum of areaType

### ISSUE THREAD

**Issue by mhfoo** [camaraproject/DeviceLocation#136]
**Problem description**
To correct YAML examples to use upper case enum of areaType:
- CIRCLE

**Expected action**
Correction of the YAMLs to reflect the correct enum

**Additional context**
enum for areaType introduced in #132

**Comment by mhfoo** [comment]
Correct the following to reflect `radius` as well, instead of `accuracy`:

```
    example:
        areaType: Circle
        center:
          latitude: 50.735851
          longitude: 7.10066
        accuracy: 50000
```
