### ISSUE TITLE
Small typo in `GENERIC_422_UNSUPPORTED_DEVICE_IDENTIFIERS` - example

### ISSUE THREAD

**Issue by maxl2287** [camaraproject/DeviceLocation#260]
**Problem description**
Incorrect reading in `"Supported device supported are: ..."`

```yaml
            GENERIC_422_UNSUPPORTED_DEVICE_IDENTIFIERS:
              summary: None of the provided device identifiers is supported by the implementation
              description: Message may list the supported device identifiers
              value:
                status: 422
                code: UNSUPPORTED_DEVICE_IDENTIFIERS
                message: "Supported device supported are: ..."
```

**Expected behavior**
```yaml
message: "Supported device identifiers are: ..."
```

**Alternative solution**

Without listing the supported device identifiers.
```
            GENERIC_422_UNSUPPORTED_DEVICE_IDENTIFIERS:
              summary: None of the provided device identifiers is supported by the implementation
              description: Message identifies that none of the provided device identifiers are supported
              value:
                status: 422
                code: UNSUPPORTED_DEVICE_IDENTIFIERS
                message: None of the provided device identifiers is supported by the implementation
```
