### ISSUE TITLE
[geofencing-subscriptions]: MultieventSubscriptionNotSupported instead of PermissionDenied.

### ISSUE THREAD

**Issue by dfischer-tech** [camaraproject/DeviceLocation#266]
**Problem description**
The example for CreateSubscriptionUnprocessableEntity422 - MultieventSubscriptionNotSupported instead of PermissionDenied.

```
MultieventSubscriptionNotSupported:
  value:
    status: 422
      code: MULTIEVENT_SUBSCRIPTION_NOT_SUPPORTED
      message: Multi event types subscription not managed
```
