### ISSUE TITLE
Allow zero-length strings in x-correlator header

### ISSUE THREAD

**Issue by bigludo7** [camaraproject/DeviceLocation#293]
**Problem description**
Allow zero-length strings in x-correlator header
As defined here https://github.com/camaraproject/Commonalities/pull/387

**Expected behavior**
Add/fix `pattern`

```
  headers:
    x-correlator:
      description: Correlation id for the different services
      schema:
        type: string
        pattern: ^[a-zA-Z0-9-]{0,55}$
```

**Alternative solution**

**Additional context**
