### ISSUE TITLE
Updated message field and description for Error 429

### ISSUE THREAD

**Issue by bigludo7** [camaraproject/DeviceLocation#294]
**Problem description**
Updated message field and description for Error 429
Defined in Commonalities https://github.com/camaraproject/Commonalities/pull/390 

**Expected behavior**
Align as following:

```
          examples:
            GENERIC_429_QUOTA_EXCEEDED:
              description: Request is rejected due to exceeding a business quota limit
              value:
                status: 429
                code: QUOTA_EXCEEDED
                message: Out of resource quota.
            GENERIC_429_TOO_MANY_REQUESTS:
              description: Access to the API has been temporarily blocked due to rate or spike arrest limits being reached
              value:
                status: 429
                code: TOO_MANY_REQUESTS
                message: Rate limit reached.
```

**Alternative solution**

**Additional context**
