### ISSUE TITLE
Missing error 422 with code LOCATION_RETRIEVAL.UNABLE_TO_FULFILL_MAX_SURFACE

### ISSUE THREAD

**Issue by dfischer-tech** [camaraproject/DeviceLocation#299]
**Problem description**
In the specification "location-retrieval.yaml" _info.description_, the parameter and the error case are well described. 
However, the possible response code representation for "RetrieveLocationUnprocessableEntity422" is missing.
Missing error 422 with code LOCATION_RETRIEVAL.UNABLE_TO_FULFILL_MAX_SURFACE

**Expected behavior**
Add the missing error 422 with code LOCATION_RETRIEVAL.UNABLE_TO_FULFILL_MAX_SURFACE
Please also provide an example, like:
```yaml

            LOCATION_RETRIEVAL_422_UNABLE_TO_FULFILL_MAX_SURFACE:
              summary: Unable to fulfill maxSurface
              description: The system is not able to provide accurate acceptable surface required by the client
              value:
                status: 422
                code: LOCATION_RETRIEVAL.UNABLE_TO_FULFILL_MAX_SURFACE
                message: "Unable to provide accurate acceptable surface for location"
```
