### ISSUE TITLE
Links in .github/ISSUE_TEMPLATE/config.yml need to be updated

### ISSUE THREAD

**Issue by maxl2287** [camaraproject/DeviceLocation#325]
**Problem description**
- The link to the `discussions` can be added here
- The CAMARA API Design Guidelines was moved to: https://github.com/camaraproject/Commonalities/blob/main/documentation/CAMARA-API-Design-Guide.md
``` 
blank_issues_enabled: true
contact_links:
  - name: 📖 CAMARA API Design Guidelines
    url: https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/API-design-guidelines.md
    about: Please refer to the design guidelines.
```
