### ISSUE TITLE
Update `sink` with pattern and corresponding Error-code

### ISSUE THREAD

**Issue by maxl2287** [camaraproject/DeviceLocation#356]
**Problem description**
`sink` needs to have a pattern and a dedicated 400 - error-code

**Possible evolution**
```yaml
 sink:
          type: string
          format: uri
          pattern: ^https:\/\/.+$
```
