### ISSUE TITLE
Add Postal Code as a type of Area

### ISSUE THREAD

**Issue by jlurien** [camaraproject/DeviceLocation#39]
Postal codes are a common user friendly denominations for known areas. 

Proposal is to add a new type of Area `PostalCode`

```
PostalCode:
  type: object
  required:
    - type
    - postalCode
  properties:
    type:
      type: string
      enum:
        - PostalCode
      description: Type of this area
    postalCode:
      type: string
      description: Postal Code (aka Zip code or Postcode), according to the local format. 
    countryCode:
      type: string
      pattern: '^[A-Z]{2}$' 
      description: ISO 3166-1 alpha-2 code for the country. Uppercase. If not specified, each implementation may apply a default value.
```

Optionally a country code may be needed in some global scenarios. Otherwise, each implementation may assume its own country.
There is no global pattern for postal codes. We could define some limits minLength , maxLength, apparently longest one is 10, but it may be better to leave all format verification to implementations.

**Comment by bigludo7** [comment]
To provide my feedback.... in France we have postalCode but another code is used for geographic purpose: the INSEE code (the postal code is more an administrative one).
Perhaps same situation could occur in other country. 
We have several options to accommodate this:

1) make a model more generic with for example a `code` attribute (to provide code value) and a `codeType`  (to provide the ype of code provided). 

````yaml
GeoCode:
  type: object
  required:
    - type
    - code
    - codeType
  properties:
    type:
      type: string
      enum:
        - GeoCode
      description: Type of this area
    code:
      type: string
      description: Code (aka Zip code or Postcode), according to the code type. 
    codeType:
      type: string
      description: Type of code (could be Postcode, INSEE Code, etc...), 
    countryCode:
      type: string
      pattern: '^[A-Z]{2}$' 
      description: ISO 3166-1 alpha-2 code for the country. Uppercase. If not specified, each implementation may apply a default value.
````

2/ leverage the polymorphic model and provide explicit specialization. In this case we keep your proposal and for example I add a structure for inseeCode.

I think that for a developer, option 2 is probably better as more explicit, but we need to find a way to expose by code the model managed by an implementation (If Telefonica managed Circle & postalCode while Orange manage Circle & insee code and then DT Circle & polygon ...developer should be able to get this information on the fly).
